import { FormEvent, useState } from 'react'
import { Link } from 'react-router-dom'
import { FileSearch, MessageSquare, RefreshCw } from 'lucide-react'
import type { Act, State } from './RecruitingPage'
type Conversation = State['conversations'][number]
type Draft = State['outbox'][number]
const statusLabels: Record<string, string> = { draft: '待确认', expired: '上下文已变化', cancelled: '已取消', sending: '执行中', sent: '已核对发出', uncertain: '发送结果待核实' }
const actionLabels: Record<string, string> = { reply: '回复', request_resume: '索取简历', accept_resume: '接收简历', invitation: '面试安排' }
const dimLabels: Record<string, string> = { duties: '核心职责', skills: '岗位技能', experience: '相关经验', requirements: '必要资格' }
const basisLabels: Record<string, string> = { conversation: '双方对话', company: '公司说明', job: '岗位 JD', resume: '简历', assessment: '岗位评估' }
const fmt = (value?: string | null) => value ? new Date(value).toLocaleString('zh-CN', { hour12: false }) : '尚未同步'
const candidateUrl = (c: Conversation, panel = 'reply') => `/recruiting/candidates/${encodeURIComponent(c.id)}?panel=${panel}`
const latestMessage = (c: Conversation) => c.snapshot.messages[c.snapshot.messages.length - 1]
export const currentAssessment = (s: State, c: Conversation) => s.assessments.find(a => a.conversation_id === c.id && a.result.document_id === s.documents.find(d => d.conversation_id === c.id)?.id && a.result.position_version === s.positions.find(p => p.id === c.position_id)?.version)

export function Monitor({ data, act, busy }: { data: State; act: Act; busy: boolean }) {
  const workerAlive = data.worker?.alive ?? false
  return <section className="rc-panel"><div className="rc-section-heading"><h3>消息监测</h3><span className={`rc-tag ${data.monitor.running ? 'good' : ''}`}>{data.monitor.running ? '运行中' : '已停止'}</span></div><p className="rc-muted">新消息同步上下文；收到简历 → 自动读取 → 按岗位 JD 评分</p><div className="rc-context-strip"><MessageSquare size={17} /><span>每次都带入对话上下文<br /><small>公司说明 + 当前岗位 JD + 已有简历</small></span></div><div className="rc-actions"><button className="primary" disabled={busy || !data.conversations.length || (!data.monitor.running && !workerAlive)} onClick={() => act(data.monitor.running ? 'monitor/stop' : 'monitor/start', {}, data.monitor.running ? '监测已停止' : '监测已开启，不自动外发')}>{data.monitor.running ? '停止监测' : '开启消息与简历监测'}</button><button disabled={busy || !data.conversations.length} onClick={() => act('monitor/once', {}, '会话检查完成')}><RefreshCw size={14} />检查一次</button></div>{!workerAlive && <p className="rc-alert warning">独立监测进程未运行：请先在终端运行 <code>bosshunter recruiting-worker</code>，再开启监测。</p>}{data.send_channel && !data.send_channel.available && <p className="rc-alert warning">发送通道不可用：{data.send_channel.message}。新回复会留草稿，待 Chrome/标签恢复后再发。</p>}{!data.model_ready && <p className="rc-caption">先<Link to="/recruiting/settings">配置模型</Link>，再开启消息与简历监测。</p>}<p className="rc-caption">每 {data.monitor.interval_seconds} 秒核对一次 · {fmt(data.monitor.last_success)}</p>{data.monitor.error && <p className="rc-alert error">{data.monitor.error}</p>}</section>
}
export function ResumePanel({ data, c, act, busy }: { data: State; c: Conversation; act: Act; busy: boolean }) {
  const doc = data.documents.find(d => d.conversation_id === c.id)
  const assessment = currentAssessment(data, c)
  const processing = data.resume_processing?.[c.id]
  const [resume, setResume] = useState('')
  const [complete, setComplete] = useState(false)
  return <div className="rc-form"><h3>简历与岗位匹配</h3><p className="rc-muted">收到简历后自动读取并按岗位 JD 评分；缺失证据保留待确认。</p><div className="rc-actions"><button disabled={busy} onClick={() => act('resume/read', { conversation_id: c.id }, '已读取简历，自动评分进度见下方')}>{processing?.status === 'read_failed' ? '重新读取简历' : '读取已收到的简历'}</button><button className="primary" disabled={busy || !doc || !data.model_ready} onClick={() => act('assess', { conversation_id: c.id }, '岗位评估已生成')}><FileSearch size={15} />{processing?.status === 'failed' ? '重试评分' : assessment ? '检查评分' : '立即评分'}</button></div>{processing?.message && <p className={`rc-alert ${['failed', 'read_failed'].includes(processing.status) ? 'warning' : ''}`} role="status">{processing.message}</p>}{!data.monitor.running && <p className="rc-caption">监测已停止。开启消息与简历监测后，新收到的简历会自动处理。</p>}{doc?.meta?.note && <p className="rc-caption" role="status">{doc.meta.filename && <strong>{doc.meta.filename}<br /></strong>}{doc.meta.note}</p>}{doc ? <details open><summary>简历原文 · {doc.complete ? '已核对完整' : '完整性待核对'}</summary><pre className="rc-document">{doc.text}</pre></details> : <p className="rc-empty rc-muted">尚未读取简历</p>}{assessment ? <div className="rc-assessment"><div className="rc-section-heading"><h3>匹配依据</h3><span className="rc-score">{assessment.result.score ?? '已评估'}</span></div><p className="rc-caption">证据覆盖率 {assessment.result.coverage}% · 已评估部分 {assessment.result.earned}/{assessment.result.assessed_weight}</p>{Object.entries(assessment.result.components).map(([key, value]) => <details key={key}><summary>{dimLabels[key]} · {value.score ?? '待确认'}</summary><p>{value.reason}</p>{value.quotes.map((q, i) => <blockquote key={i}>{q}</blockquote>)}</details>)}{assessment.result.questions.map((q, i) => <p key={i}>待确认：{q}</p>)}</div> : <p className="rc-caption">暂无当前资料对应的评分。{!data.model_ready ? '需先配置模型。' : ''}</p>}<details className="rc-context-details"><summary>核对或补全简历</summary><div className="rc-form">{doc && <button type="button" onClick={() => { setResume(doc.text); setComplete(false) }}>载入已有文字</button>}<label>简历文字<textarea rows={8} value={resume} onChange={e => setResume(e.target.value)} /></label><label className="rc-check"><input type="checkbox" checked={complete} onChange={e => setComplete(e.target.checked)} />已核对全部页，确认资料完整</label><button disabled={busy || resume.trim().length < 50} onClick={() => act('resume/save', { conversation_id: c.id, text: resume, complete }, '已保存核对后的简历')}>保存核对版本</button></div></details></div>
}
export function Drafts({ drafts, act, busy, inline = false, onEdit }: { drafts: Draft[]; act: Act; busy: boolean; inline?: boolean; onEdit?: (text: string) => void }) {
  return <section className={inline ? 'rc-inline-results' : 'rc-panel'}><h3>处理结果</h3>{drafts.length ? drafts.map(d => <div className="rc-draft" key={d.id}><div className="rc-section-heading"><strong>{actionLabels[d.kind]}</strong><span className={`rc-tag ${d.status === 'uncertain' ? 'warning' : ''}`}>{statusLabels[d.status]}</span></div><p className="rc-pre">{d.kind === 'invitation' ? Object.values(JSON.parse(d.content)).join(' · ') : d.content || '等待核对平台简历卡片'}</p>{d.refs.source === 'ai_draft' && <p className="rc-caption">结合 {d.refs.message_count ?? '历史'} 条消息 · {(d.refs.basis || []).map(b => basisLabels[b]).join('、')}</p>}{d.refs.needs_human && <p className="rc-alert warning">需要人工确认：{d.refs.missing?.join('；') || '上下文依据不足'}</p>}{d.result && <p className="rc-caption">{d.result}</p>}{d.status === 'draft' && <div className="rc-actions">{d.kind === 'reply' && onEdit && <button disabled={busy} onClick={() => onEdit(d.content)}>编辑这段回复</button>}<button className="primary" disabled={busy || d.kind === 'invitation' || d.refs.needs_human} onClick={() => act('outbox/execute', { id: d.id }, '本次尝试结束，请查看结果状态')}>{d.kind === 'invitation' ? '面试邀约发送已禁用' : '确认并执行'}</button><button disabled={busy} onClick={() => act('outbox/cancel', { id: d.id }, '已取消')}>取消</button></div>}</div>) : <p className="rc-muted">暂未生成回复或执行动作。</p>}</section>
}
export function InvitationForm({ c, act, busy }: { c: Conversation; act: Act; busy: boolean }) {
  const [mode, setMode] = useState('online'), [time, setTime] = useState(''), [place, setPlace] = useState(''), [contact, setContact] = useState('')
  const submit = (e: FormEvent) => { e.preventDefault(); act('invitations/draft', { conversation_id: c.id, mode, scheduled_at: new Date(time).toISOString(), location: place, contact }, '面试安排已保存在本地，未发送') }
  return <form className="rc-form" onSubmit={submit}><h3>面试安排</h3><p className="rc-alert warning">当前测试禁止发送面试邀约。这里只保留本地安排。</p><label>方式<select value={mode} onChange={e => setMode(e.target.value)}><option value="online">线上</option><option value="offline">线下</option></select></label><label>日期和时间<input required type="datetime-local" value={time} onChange={e => setTime(e.target.value)} /></label><label>{mode === 'online' ? '会议方式或链接' : '面试地址'}<input required value={place} onChange={e => setPlace(e.target.value)} /></label><label>联系人<input required value={contact} onChange={e => setContact(e.target.value)} /></label><button disabled={busy}>保存本地安排</button></form>
}
