import { Link } from 'react-router-dom'
import { ArrowRight, ChevronRight, CircleAlert, Pause, Settings2 } from 'lucide-react'
import { RecruitIcon } from '../components/recruiting/RecruitIcon'
import { GreetingQuota } from '../components/recruiting/GreetingQuota'
import type { State, Act } from './RecruitingPage'
const time = (value: string) => new Date(value).toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit', hour12: false })
export function RecruitingOverview({ data, act, busy }: { data: State; act: Act; busy: boolean }) {
  const jobs = data.recruiting_jobs
  const selected = jobs?.jobs.filter(j => j.selected) || []
  const shownJobs = selected.length ? selected : (jobs?.jobs.filter(j => j.status === '开放中') || []).slice(0, 4)
  const pendingReplies = data.conversations.filter(c => c.snapshot.messages[c.snapshot.messages.length - 1]?.direction === 'in' && !c.taken_over && !c.do_not_contact).length
  const currentAssessment = (cid: string) => {
    const c = data.conversations.find(c => c.id === cid)
    return data.assessments.find(a => a.conversation_id === cid && a.result.document_id === data.documents.find(d => d.conversation_id === cid)?.id && a.result.position_version === data.positions.find(p => p.id === c?.position_id)?.version)
  }
  const pendingResumes = data.conversations.filter(c => data.documents.some(d => d.conversation_id === c.id) && !currentAssessment(c.id)).length
  const tasks = data.conversations.map(c => {
    const uncertain = data.outbox.some(o => o.conversation_id === c.id && o.status === 'uncertain')
    const last = c.snapshot.messages[c.snapshot.messages.length - 1]
    const needsResume = data.documents.some(d => d.conversation_id === c.id) && !currentAssessment(c.id)
    const label = c.do_not_contact ? '已停止联系' : c.taken_over ? '人工处理中' : uncertain ? '发送结果待核实' : last?.direction === 'in' ? '等待处理回复' : needsResume ? '简历待评估' : '等待对方回复'
    return { c, last, label, attention: uncertain || last?.direction === 'in' || needsResume }
  }).sort((a, b) => Number(b.attention) - Number(a.attention))
  const events = data.events.slice(0, 5)
  return <>
    <div className="rd-page-heading"><div><h2>今天的招聘进展</h2><p>从岗位选择到候选人沟通，让每一步都有明确的下一步。</p></div><div className="rd-heading-actions"><span className="rd-date">{new Date().toLocaleDateString('zh-CN', { month: 'long', day: 'numeric', weekday: 'long' })}</span><Link className="rd-button primary" to="/recruiting/positions"><Settings2 size={15} />管理自动招聘</Link></div></div>
    <GreetingQuota data={jobs} />
    <div className="rd-metrics"><Link to="/recruiting/positions"><RecruitIcon name="jobs" size={41} /><div><span>已选岗位</span><strong>{selected.length}</strong></div><small>{selected.length ? '等待执行接通' : '先选择招聘范围'}</small></Link><Link to="/recruiting/candidates"><RecruitIcon name="chat" size={42} /><div><span>待回复</span><strong>{pendingReplies}</strong></div><small>结合完整上下文处理</small></Link><Link to="/recruiting/candidates"><RecruitIcon name="resume" size={41} /><div><span>待评估简历</span><strong>{pendingResumes}</strong></div><small>核对岗位匹配依据</small></Link></div>
    <div className="rd-dashboard-grid"><div className="rd-main-stack">
      <section className="rd-panel"><div className="rd-panel-heading"><h3>需要处理 <span className="rd-count">{tasks.filter(t => t.attention).length}</span></h3><Link to="/recruiting/candidates">全部候选人 <ChevronRight size={14} /></Link></div><div className="rd-task-list">{tasks.slice(0, 5).map(({ c, last, label, attention }) => <div className="rd-person-task" key={c.id}><span className="rd-person-avatar">{c.name.slice(0, 1)}</span><div className="rd-person-name"><strong>{c.name}</strong><small>{data.positions.find(p => p.id === c.position_id)?.title || '岗位待核对'}</small></div><div className="rd-person-message"><p>{last?.text || '暂无已加载消息'}</p><small>{time(c.updated_at)} 更新</small></div><span className={`rd-badge${attention ? ' amber' : ''}`}>{label}</span><Link to={`/recruiting/candidates/${encodeURIComponent(c.id)}`}>进入沟通 <ChevronRight size={13} /></Link></div>)}{!tasks.length && <div className="rd-empty"><RecruitIcon name="chat" size={34} /><p>还没有已同步的候选人</p><Link to="/recruiting/candidates">前往候选人沟通 <ArrowRight size={14} /></Link></div>}</div>
                {(!data.model_ready || !data.company?.text || !data.conversations.length) && <div className="rd-setup-tasks">{!data.conversations.length && <Link to="/recruiting/binding"><CircleAlert size={15} /><span>尚未绑定候选人会话</span><span>去绑定 <ChevronRight size={13} /></span></Link>}{!data.model_ready && <Link to="/recruiting/settings"><CircleAlert size={15} /><span>回复和评分模型尚未配置</span><span>去配置 <ChevronRight size={13} /></span></Link>}{!data.company?.text && <Link to="/recruiting/company"><CircleAlert size={15} /><span>补充公司说明，给回复提供依据</span><span>去填写 <ChevronRight size={13} /></span></Link>}</div>}
      </section>
      <section className="rd-panel"><div className="rd-panel-heading"><h3>岗位运行情况</h3><Link to="/recruiting/positions">管理岗位 <ChevronRight size={14} /></Link></div><div className="rd-table-scroll"><table className="rd-table rd-operation-table"><thead><tr><th>岗位名称</th><th>今日招呼</th><th>处理状态</th><th>操作</th></tr></thead><tbody>{shownJobs.map(j => <tr key={j.id}><td><strong>{j.title}</strong><small>{j.details[0] || '地点待核对'}</small></td><td className="rd-subtle">—</td><td><span className="rd-state"><i />{j.selected ? '已选 · 待接通' : '未勾选'}</span></td><td><Link to="/recruiting/positions">配置 <ChevronRight size={13} /></Link></td></tr>)}</tbody></table></div>{!shownJobs.length && <p className="rd-empty">先同步已发布岗位，再选择自动处理范围。</p>}<p className="rd-table-note">{selected.length ? '主动打招呼尚未接通，目前不会自动外发。' : '尚未勾选岗位，以上为开放岗位预览。'}岗位招呼明细暂无数据。</p></section>
    </div><aside className="rd-agent-panel rd-panel"><div className="rd-panel-heading"><h3>Agent {data.monitor.running ? '监测中' : '待启动'}</h3><span className={`rd-state${data.monitor.running ? ' green' : ''}`}><i />{data.monitor.running ? '生成草稿' : '尚未开启'}</span></div><ol className="rd-agent-steps"><li><span className="rd-step-number">1</span><RecruitIcon name="search" size={29} /><div><strong>找人与打招呼</strong><p>在已选岗位范围内寻找候选人，共用每日招呼额度。</p><Link to="/recruiting/positions">{selected.length ? `已选 ${selected.length} 个岗位 · 执行待接通` : '先选择允许处理的岗位'} <ChevronRight size={12} /></Link></div></li><li><span className="rd-step-number">2</span><RecruitIcon name="chat" size={29} /><div><strong>读取上下文回复</strong><p>双方对话、公司说明和岗位 JD，一起交给 Agent。</p><Link to={data.model_ready ? '/recruiting/candidates' : '/recruiting/settings'}>{data.model_ready ? data.monitor.running ? '正在监测 · 不自动外发' : '回复草稿监测未开启' : '待配置模型'} <ChevronRight size={12} /></Link></div></li><li><span className="rd-step-number">3</span><RecruitIcon name="resume" size={29} /><div><strong>简历匹配评估</strong><p>逐项核对职业经历和岗位要求，缺失资料保留待确认。</p><Link to="/recruiting/candidates">{pendingResumes} 份简历待评估 <ChevronRight size={12} /></Link></div></li></ol><div className="rd-activity"><div className="rd-panel-heading"><h4>最近活动</h4><Link to="/recruiting/monitor">查看全部 <ChevronRight size={12} /></Link></div>{events.map(e => <div className="rd-activity-row" key={e.id}><time>{time(e.created_at)}</time><p>{e.detail || '招聘状态已更新'}</p></div>)}{!events.length && <p className="rd-small">任务执行后，进展会显示在这里。</p>}</div>{data.monitor.error && <p className="rd-inline-warning">{data.monitor.error}</p>}{data.monitor.running ? <button className="rd-button danger rd-wide" disabled={busy} onClick={() => act('monitor/stop', {}, '回复草稿监测已停止')}><Pause size={15} />停止回复监测</button> : <Link className="rd-button rd-wide" to={!selected.length ? '/recruiting/positions' : '/recruiting/settings'}>完成运行准备 <ArrowRight size={15} /></Link>}<p className="rd-agent-footnote">当前为单候选人试运行，面试邀约发送已禁用。</p></aside></div>
  </>
}
